# Simple configuration for code generation system
openai:
  model: "gpt-4o-mini-2024-07-18"
  max_tokens: 1000
  temperature: 0.7

generation:
  min_functions: 2
  max_functions: 4
  include_main: true

output:
  directory: "output"
  save_metadata: true

execution:
  timeout_seconds: 10
  max_memory_mb: 128