# Pipeline Configuration for Code Output Prediction System

# Pipeline Settings
pipeline:
  num_samples: 10                    # Number of code samples to generate
  resume_from: null                  # Sample ID to resume from (null = start fresh)
  output_dir: "data/pipeline_results" # Output directory for all results
  intermediate_save: true            # Save intermediate results
  save_interval: 5                   # Save state every N samples

# Code Generation Settings
code_generation:
  config_path: "configs/code_generator.yaml"  # Path to code generator config
  retry_attempts: 3                  # Number of retry attempts for failed generations
  timeout_seconds: 60                # Timeout for code generation API calls

# Input Generation Settings  
input_generation:
  inputs_per_code: 8                 # Target number of inputs per code sample
  max_input_variants: 10             # Maximum input variants to generate
  include_edge_cases: true           # Include edge cases in input generation
  
# Execution Settings
execution:
  timeout_seconds: 10                # Maximum execution time per code run
  max_memory_mb: 256                 # Maximum memory usage per execution
  max_concurrent: 1                  # Number of concurrent executions (not implemented yet)
  retry_failures: true               # Retry failed executions once

# Logging Configuration
logging:
  level: "INFO"                      # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: null                         # Log file path (null = console only)
  console: true                      # Enable console logging
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Progress Tracking
progress:
  show_progress_bars: true           # Show tqdm progress bars
  detailed_logging: true             # Enable detailed step logging
  save_statistics: true              # Save performance statistics

# Data Export Settings
export:
  format: "json"                     # Export format (json, csv - future)
  include_metadata: true             # Include generation metadata
  compress_results: false            # Compress output files (future)
  split_by_success: false            # Split successful/failed executions (future)

# Performance Tuning
performance:
  batch_size: 1                      # Process samples in batches (future)
  parallel_executions: false         # Enable parallel execution (future)
  cache_results: true                # Cache intermediate results
  cleanup_temp_files: true           # Clean up temporary files after each sample

# Error Handling
error_handling:
  max_retries: 3                     # Maximum retry attempts
  retry_delay: 1.0                   # Delay between retries (seconds)
  fail_fast: false                   # Stop on first error (false = continue)
  save_failed_samples: true          # Save data for failed samples

# Resource Monitoring
monitoring:
  track_memory_usage: true           # Monitor memory usage
  track_execution_time: true         # Track detailed timing
  save_performance_metrics: true     # Save performance data
  alert_on_high_failure_rate: false  # Alert if failure rate > threshold (future)