# Configuration for Python Code Executor

# Security Limits
security:
  timeout_seconds: 30           # Maximum execution time
  max_memory_mb: 256           # Maximum memory usage
  max_output_size: 1048576     # Maximum output size (1MB)
  max_file_size: 10485760      # Maximum file size (10MB)
  
  # Module restrictions
  blocked_modules:
    - subprocess
    - os
    - sys
    - shutil
    - socket
    - urllib
    - requests
    - http
    - ftplib
    - smtplib
    - __import__
    - eval
    - exec
    - compile
  
  # Optional: Allow specific modules only (null = allow all except blocked)
  allowed_modules: null

# Logging Configuration
logging:
  level: INFO                  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null                   # null = console only, or path to log file

# Execution Environment
environment:
  python_executable: "python"  # Python executable to use
  working_directory: null      # null = use temporary directory
  preserve_temp_files: false   # Keep temporary files for debugging
  
  # Environment variables to set
  env_vars:
    PYTHONDONTWRITEBYTECODE: "1"
    PYTHONUNBUFFERED: "1"
    PYTHONIOENCODING: "utf-8"

# Output Configuration
output:
  capture_stdout: true
  capture_stderr: true
  include_metadata: true
  format_json: false           # Format outputs as JSON
  timestamp_format: "%Y-%m-%d %H:%M:%S"

# Resource Monitoring
monitoring:
  track_memory: true
  track_cpu: true
  sample_interval: 0.1         # seconds

# Platform-specific settings
platform:
  # Unix-specific resource limits
  unix:
    enable_rlimit: true
    max_open_files: 100
    max_processes: 10
  
  # Windows-specific settings
  windows:
    job_object_limits: true